// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emwgbdwpjicxtbuilwqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtd2diZHdwamljeHRidWlsd3F1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyNTE1ODUsImV4cCI6MjA1NTgyNzU4NX0.VA-l0-W3MMp2S2ThSUBqR2y0xrniP_GD3tvVnsqmJJY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);